name: PayNow
author: PayNow
version: 1.0
main: gg.paynow.paynowbukkit.PayNowBukkit
api-version: 1.13

commands:
  paynow:
    description: PayNow command
    usage: /paynow
    permission: paynow.admin
    aliases: [pn]